/*
 * Lolipad
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type RegisterRequest struct {

	Msisdn string `json:"msisdn"`

	Name string `json:"name"`

	Username string `json:"username"`

	Password string `json:"password"`
}
