/*
 * Lolipad
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"//",
		Index,
	},

	Route{
		"CheckToken",
		strings.ToUpper("Get"),
		"//auth/check-token",
		CheckToken,
	},

	Route{
		"Login",
		strings.ToUpper("Post"),
		"//auth/",
		Login,
	},

	Route{
		"Register",
		strings.ToUpper("Post"),
		"//auth/register",
		Register,
	},

	Route{
		"GetAll",
		strings.ToUpper("Get"),
		"//logistic/all",
		GetAll,
	},

	Route{
		"GetData",
		strings.ToUpper("Get"),
		"//logistic",
		GetData,
	},
}
